# These are supported funding model platforms

github: swar
patreon: swar
open_collective: # Replace with a single Open Collective username
ko_fi: swarpatel
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["https://www.chiaexplorer.com/blockchain/address/xch134evwwqkq50nnsmgehnnag4gc856ydc7ached3xxr6jdk7e8l4usdnw39t", "https://etherscan.io/address/0xf8F7BD24B94D75E54BFD9557fF6904DBE239322E", "https://www.blockchain.com/btc/address/36gnjnHqkttcBiKjjAekoy68z6C3BJ9ekS", "https://www.paypal.com/biz/fund?id=XGVS7J69KYBTY"]
